### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tnttol** [vanhbakaa/battle-bull#6]
```
Traceback (most recent call last):
  File "/home/name/bots/battle-bull/bot/core/tapper.py", line 398, in run
    await self.upgrade(session)
  File "/home/name/bots/battle-bull/bot/core/tapper.py", line 291, in upgrade
    if card['condition'] is None and int(self.balance) >= int(card['nextLevel']['cost']):
                                                              ~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by vanhbakaa** [comment]
fixed
